GET  https://ev4w443k4g.execute-api.eu-central-1.amazonaws.com/prod/prod/spaces
###

POST https://ev4w443k4g.execute-api.eu-central-1.amazonaws.com/prod/spaces
content-type: application/json

{"location": "Berlin 3"}
###